"""Initial schema

Revision ID: 725e6e0e9cdd
Revises: 
Create Date: 2025-11-28 21:31:58.689209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725e6e0e9cdd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('PLAYER', 'COACH', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('match_type', sa.Enum('SINGLES', 'DOUBLES', 'PRACTICE', name='matchtype'), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'PROCESSING', 'ANALYZING', 'COMPLETED', 'FAILED', name='matchstatus'), nullable=True),
    sa.Column('player1_name', sa.String(), nullable=True),
    sa.Column('player2_name', sa.String(), nullable=True),
    sa.Column('match_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('court_surface', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('processing_progress', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_table('match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player1_stats', sa.JSON(), nullable=False),
    sa.Column('player2_stats', sa.JSON(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('total_rallies', sa.Integer(), nullable=True),
    sa.Column('total_shots', sa.Integer(), nullable=True),
    sa.Column('player1_heatmap', sa.JSON(), nullable=True),
    sa.Column('player2_heatmap', sa.JSON(), nullable=True),
    sa.Column('highlights', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_index(op.f('ix_match_stats_id'), 'match_stats', ['id'], unique=False)
    op.create_table('match_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_videos_id'), 'match_videos', ['id'], unique=False)
    op.create_table('player_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('court_x', sa.Float(), nullable=True),
    sa.Column('court_y', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Float(), nullable=True),
    sa.Column('distance_from_center', sa.Float(), nullable=True),
    sa.Column('pose_keypoints', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_movements_id'), 'player_movements', ['id'], unique=False)
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=True),
    sa.Column('game_number', sa.Integer(), nullable=True),
    sa.Column('point_number', sa.Integer(), nullable=True),
    sa.Column('winner_player', sa.Integer(), nullable=True),
    sa.Column('point_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('score', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_id'), 'points', ['id'], unique=False)
    op.create_table('rallies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('shot_count', sa.Integer(), nullable=False),
    sa.Column('winner_player', sa.Integer(), nullable=True),
    sa.Column('ended_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rallies_id'), 'rallies', ['id'], unique=False)
    op.create_table('shots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('rally_id', sa.Integer(), nullable=True),
    sa.Column('player_number', sa.Integer(), nullable=False),
    sa.Column('shot_type', sa.Enum('FOREHAND', 'BACKHAND', 'VOLLEY', 'SLICE', 'DROP_SHOT', 'OVERHEAD', 'SERVE', 'RETURN', name='shottype'), nullable=False),
    sa.Column('outcome', sa.Enum('WINNER', 'ERROR', 'UNFORCED_ERROR', 'FORCED_ERROR', 'IN_PLAY', 'LET', 'FAULT', 'ACE', name='shotoutcome'), nullable=True),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('court_x', sa.Float(), nullable=True),
    sa.Column('court_y', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('spin_type', sa.String(), nullable=True),
    sa.Column('speed_estimate', sa.Float(), nullable=True),
    sa.Column('pose_keypoints', sa.JSON(), nullable=True),
    sa.Column('swing_phase', sa.String(), nullable=True),
    sa.Column('ball_trajectory', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['rally_id'], ['rallies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shots_id'), 'shots', ['id'], unique=False)
    op.create_table('serves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=True),
    sa.Column('shot_id', sa.Integer(), nullable=True),
    sa.Column('player_number', sa.Integer(), nullable=False),
    sa.Column('serve_number', sa.Integer(), nullable=False),
    sa.Column('serve_type', sa.String(), nullable=True),
    sa.Column('placement', sa.String(), nullable=True),
    sa.Column('speed_estimate', sa.Float(), nullable=True),
    sa.Column('is_fault', sa.Boolean(), nullable=True),
    sa.Column('is_ace', sa.Boolean(), nullable=True),
    sa.Column('is_double_fault', sa.Boolean(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('serve_box', sa.String(), nullable=True),
    sa.Column('landing_x', sa.Float(), nullable=True),
    sa.Column('landing_y', sa.Float(), nullable=True),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['point_id'], ['points.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serves_id'), 'serves', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_serves_id'), table_name='serves')
    op.drop_table('serves')
    op.drop_index(op.f('ix_shots_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_rallies_id'), table_name='rallies')
    op.drop_table('rallies')
    op.drop_index(op.f('ix_points_id'), table_name='points')
    op.drop_table('points')
    op.drop_index(op.f('ix_player_movements_id'), table_name='player_movements')
    op.drop_table('player_movements')
    op.drop_index(op.f('ix_match_videos_id'), table_name='match_videos')
    op.drop_table('match_videos')
    op.drop_index(op.f('ix_match_stats_id'), table_name='match_stats')
    op.drop_table('match_stats')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
